AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Handle wallet operations
Parameters:
  DBName:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: WalletDBName
  DBMasterUserName:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: WalletDBMasterUserName
  DBMasterPassword:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: WalletDBMasterPassword
Resources:
  MigrateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Policies:  !Ref MigrateFunctionRole
      CodeUri: ./
      Environment:
        Variables:
          DB_ENDPOINT_ADDRESS: !GetAtt WalletDB.Endpoint.Address
          DB_PORT: !GetAtt WalletDB.Endpoint.Port
          DB_NAME: !Ref DBName
          DB_USERNAME: !Ref DBMasterUserName
          DB_PASSWORD: !Ref DBMasterPassword
          DB_DRIVER: mysql

  WalletDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      DBSecurityGroups:
      - !Ref DbSecurityByEC2SecurityGroup
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Ref DBMasterPassword
      DBInstanceIdentifier: WalletDB
    DeletionPolicy: Snapshot

  DbSecurityByEC2SecurityGroup:
    Type: "AWS::RDS::DBSecurityGroup"
    Properties:
      GroupDescription: "Ingress for Amazon EC2 security group"
      DBSecurityGroupIngress:
        - CIDRIP: "0.0.0.0/0"

  MigrateFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      Policies:
        -
          PolicyName: "codepipeline"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "codepipeline:PutJobSuccessResult"
                Resource: "*"

Outputs:
  WalletDBEndpoint:
    Description: WalletDB Endpoint
    Value: !GetAtt WalletDB.Endpoint.Address
    Export:
      Name: WalletDBEndpoint
  WalletDBPort:
    Description: WalletDB Port
    Value: !GetAtt WalletDB.Endpoint.Port
    Export:
      Name: WalletDBPort